define(['jquery', 'underscore', 'backbone', 'views/ExpandCollapseListView', 'text!templates/provStatement.html'], 				
	function($, _, Backbone, ExpandCollapseList, ProvTemplate) {
	'use strict';

	
	var ProvStatementView = Backbone.View.extend({
		
		initialize: function(options){
			if((options === undefined) || (!options)) var options = {};
			
			this.id   		= options.id	 	 || null;
			this.attributes = options.attributes || null;
			this.className += options.className  || "";
		},
		
		template: _.template(ProvTemplate),
		
		tagName : "div",
		
		className : "provenance alert alert-info",
		
		events: {
			
		},
		
		/*
		 * Creates a provenance statement and inserts it into the template
		 */
		render: function(doc){
			if((doc === undefined) || !doc) return false;
			
			var view 	= this,
				hasProv = true;
			
			//Add the provenance statement HTML from the template
			this.$el.html(view.template());
			
			//Support an array of documents or a single doc
			if(!Array.isArray(doc)) doc = [doc];

			_.each(doc, function(thisDoc){
				
				//Get the provenance for this document
				var lists = view.getProvenance(thisDoc);
				
				if(!lists.length){
					view.$el.remove();
					hasProv = false;
					return;
				}
				
				//We will get an array of ID lists back.
				_.each(lists, function(list){
					//Render each ID list
					var html = list.render().el;
					//Insert the list element into the DOM
					view.$el.find(".provenance-statement").append(html);
				});
			});
				
			if(!hasProv) return false;
			
			return this;
		},
		
		getProvenance: function(doc){
			var statements = [];
			
			// Get the type of object this is
			var noun = "";
			
			//Check for images 
			if(doc.formatId.substring(0, 4) == "image")
				noun = "image";
			
			//Check for data tables
			switch(doc.formatId){
				case "text/csv": 
					noun = "table";
					break;
				case "application/vnd.ms-excel":
					noun = "table";
					break;
				case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
					noun = "table";
					break;
			}
			
			//Default to more generic terms
			if(!noun){
				if(doc.formatType == "DATA") noun = "data";
				else if(doc.formatType == "METADATA") noun = "metadata";
				else noun = "object";
			}

			//Create the provenance statement(s)
			if(doc.wasDerivedFrom && doc.wasGeneratedBy){
				var wasDerivedFrom = new ExpandCollapseList({
					list 		: doc.wasDerivedFrom,
					prependText : "This " + noun + " was derived from "
				});
				
				var wasGeneratedBy = new ExpandCollapseList({
					list 		: doc.wasGeneratedBy,
					prependText : " and was generated by ",
					appendText  : ". "
				});
				
				statements.push(wasDerivedFrom, wasGeneratedBy);
				
				/*prov += "This " + noun + " was derived from " +
						wasDerivedFrom.render().$el.html() +
						"and was generated by " +
						wasGeneratedBy.render().$el.html() +
						". ";*/
			}
			else if(doc.wasDerivedFrom){
				var wasDerivedFrom = new ExpandCollapseList({
					list 		: doc.wasDerivedFrom,
					prependText : "This " + noun + " was derived from ",
					appendText  : ". "
				});
				
				statements.push(wasDerivedFrom);
			}
			else if(doc.wasGeneratedBy){
				var wasGeneratedBy = new ExpandCollapseList({
					list 		: doc.wasGeneratedBy,
					prependText : "This " + noun + " was generated by ",
					appendText  : ". "
				});
				
				statements.push(wasGeneratedBy);
			}

			//If there is a used statement we can assume this object is a "program" or prov:Plan
			if(doc.used){
				var used = new ExpandCollapseList({
					list	    : doc.used,
					prependText : "This program used ",
					appendText  : ". "
				});
				
				statements.push(used);
			}
			
			//If there is a wasInformedBy statement we can assume this object is a "program" or prov:Plan
			if(doc.wasInformedBy){
				var wasInformedBy = new ExpandCollapseList({
					list 		: doc.wasInformedBy,
					prependText : "This program was generated by ",
					appendText  : ". "
				});
				
				statements.push(wasInformedBy);
			}
			
			return statements;
		}
	});
	
	return ProvStatementView;		
});
