apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metacatui-pvc
  namespace: mcui
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: metacatui-pv
