name: Format, Lint, & Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - "ignore-*"

jobs:
  run_checks:
    name: Run All Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for diff

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint with reviewdog
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src'
          filter_mode: 'diff_context'
  
      - name: Run Prettier with reviewdog
        uses: EPMatt/reviewdog-action-prettier@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: 'diff_context'

      - name: Run unit tests
        id: test
        run: npm test
        continue-on-error: true
        
      - name: Dry run jsdoc
        id: jsdoc-dry-run
        run: npm run jsdoc-dry-run
        continue-on-error: true
